jobs:
  verify:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Start Up
        uses: actions/checkout@v2
      - name: Download Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./verify/verify

name: Main

on:
  schedule:
    - cron: "55 0/3 * * *"
